import type { ScriptDefinition } from './types';

export const SAMPLE_SCRIPT: ScriptDefinition = {
  id: 'script-exorcism-door',
  title: '破门驱邪',
  summary: '郊外孤宅传来哭声，被邪灵附身的孩子被锁在地下室。',
  setting: '1996 年郊外小镇 · 暴雨夜',
  difficulty: '中等',
  skillOptions: [
    { id: 'spotHidden', label: '侦查', group: '调查' },
    { id: 'listen', label: '聆听', group: '调查' },
    { id: 'occult', label: '神秘学', group: '学识' },
    { id: 'psychology', label: '心理学', group: '学识' },
    { id: 'medicine', label: '医学', group: '学识' },
    { id: 'firstAid', label: '急救', group: '学识' },
    { id: 'persuade', label: '说服', group: '社交' },
    { id: 'intimidate', label: '威吓', group: '社交' },
    { id: 'stealth', label: '潜行', group: '行动' },
    { id: 'locksmith', label: '开锁', group: '行动' },
    { id: 'brawl', label: '格斗', group: '战斗' },
    { id: 'firearms', label: '枪械', group: '战斗' },
  ],
  equipmentOptions: [
    '圣水',
    '银质十字',
    '驱魔符纸',
    '手电筒',
    '撬棍',
    '绳索',
    '急救包',
    '散弹枪',
    '左轮手枪',
    '盐',
    '蜡烛',
    '录音机',
  ],
  occupationOptions: ['神父', '刑警', '民俗学者', '退伍军人', '私家侦探', '记者'],
  originOptions: ['松柏镇', '灰木镇', '旧教堂区', '码头区', '郊外农场'],
  buffOptions: ['灵感加持', '沉着冷静', '仪式专注', '团队支援', '直觉敏锐'],
  debuffOptions: ['噩梦缠身', '精神负荷', '轻微受伤', '恐惧残留', '信念动摇'],
  attributeRanges: {},
  attributePointBudget: 0,
  skillLimit: 4,
  equipmentLimit: 5,
  buffLimit: 1,
  debuffLimit: 1,
  scenes: [
    {
      id: 'scene-mansion',
      title: '封锁的老宅',
      summary: '破门闯入，屋内尽是撕裂的护符与混乱痕迹。',
      location: '格林家的老宅',
      hooks: ['符纸残片', '烧毁的圣像', '孩童哭声'],
    },
    {
      id: 'scene-basement',
      title: '地下祈祷室',
      summary: '盐圈与刻痕围出祭坛，驱魔仪式在此达成。',
      location: '地下室祈祷间',
      hooks: ['盐圈', '刻痕', '破碎祭坛'],
    },
  ],
  encounters: [
    {
      id: 'encounter-cult',
      title: '邪教徒阻击',
      summary: '护法信徒阻挡外来者进入地下室。',
      enemies: ['邪教徒 x3'],
      danger: '中',
    },
    {
      id: 'encounter-possessed',
      title: '邪灵显形',
      summary: '附身孩童失控，邪灵在仪式中现形。',
      enemies: ['被附身的孩童 x1', '影灵 x1'],
      danger: '高',
    },
  ],
};
