import type { ScriptDefinition } from './types.ts';

export const SAMPLE_SCRIPT: ScriptDefinition = {
  id: 'script-exorcism-door',
  rulesetId: 'coc-7e-lite',
  title: '破门驱邪',
  summary: '郊外孤宅传来哭声，被邪灵附身的孩子被锁在地下室。',
  setting: '1996 年郊外小镇 · 暴雨夜',
  difficulty: '中等',
  openingMessages: [
    {
      role: 'system',
      content: '剧本《破门驱邪》开场。你们受旧教堂委托，前往格林家老宅调查孩童疑似被邪灵附身的传闻。',
    },
    {
      role: 'dm',
      speaker: '肉团长',
      content: '暴雨夜的松柏镇郊外，老宅在闪电里忽明忽暗。院子里散落着被撕裂的符纸，盐圈被雨水冲成断裂的弧线。',
    },
    {
      role: 'dm',
      speaker: '肉团长',
      content: '木门被木板钉死，门缝里透出微弱的烛光。地下室的哭声断断续续，你还能听见更深处的低语。',
    },
  ],
  background: {
    overview: '格林家老宅被传出附身与驱魔失败的流言，旧教堂不愿让事态继续扩散。',
    truth: '真正的问题不是单纯附身，而是地下祈祷室中残留的失败仪式撕开了一个小型灵性裂口。',
    themes: ['信仰失效', '家庭崩塌', '失控仪式'],
    factions: ['旧教堂', '格林家残余亲属', '暗中观察的邪教徒'],
    locations: ['格林家老宅', '地下祈祷室', '旧教堂'],
    explorableAreas: [
      {
        id: 'area-yard',
        name: '老宅院子',
        summary: '暴雨冲刷的碎符与盐圈残迹。',
        description: '破旧围栏半塌，树影在闪电中摇晃，泥地上还能看见未被雨水洗净的符纸灰。',
        dmNotes: '提示符纸被撕裂是有人闯入时所为。',
      },
      {
        id: 'area-foyer',
        name: '正门与门廊',
        summary: '木门被木板钉死，烛光从门缝渗出。',
        description: '门廊上堆着旧箱子与断裂木板，门锁锈蚀但还算完整。',
        dmNotes: '破门或开锁均可进入，但会制造噪音。',
      },
      {
        id: 'area-hall',
        name: '一层走廊',
        summary: '空气潮湿，地面有拖拽痕。',
        description: '通向起居室与楼梯口，墙上挂着褪色的家族照片。',
        dmNotes: '拖拽痕可指向地下室入口。',
      },
      {
        id: 'area-basement',
        name: '地下祈祷室',
        summary: '盐圈与刻痕围出祭坛。',
        description: '墙面刻满祷文与抓痕，孩童的哭声从黑暗深处传来。',
        dmNotes: '邪灵在此地现形，战斗或驱魔关键场景。',
      },
    ],
    secrets: ['符纸被撕裂并非邪灵自己所为，而是有人先一步闯入。', '地下室的哭声会诱导调查员贸然深入。'],
  },
  storyArcs: [
    {
      id: 'arc-entry',
      title: '踏入老宅',
      summary: '调查员需要顶着暴雨进入老宅，判断这里究竟发生了什么。',
      beats: ['进入院子', '突破正门', '发现拖拽痕迹'],
      reveals: ['有人先于调查员闯入老宅'],
    },
    {
      id: 'arc-basement',
      title: '地下室显形',
      summary: '调查员在祈祷室直面失控仪式残留，并决定封印或驱散。',
      beats: ['确认哭声来源', '识别盐圈与刻痕', '处理灵体显形'],
      reveals: ['失败仪式才是灾祸根源'],
    },
  ],
  npcProfiles: [
    {
      id: 'npc-grace-neighbor',
      name: '格蕾丝太太',
      type: '受惊邻居',
      role: 'neutral',
      threat: '低',
      summary: '住在老宅附近的寡妇，昨夜目睹了异常灯光和闯入者身影。',
      useWhen: '调查员在外围打听老宅消息时',
      status: '惊魂未定',
      hp: 10,
      attacks: [],
      skills: [{ name: '心理学', value: 35 }],
      traits: ['不愿靠近老宅', '记得一顶黑色雨帽'],
      tactics: '只有在安抚后才愿意透露完整信息。',
      weakness: '容易被再次吓到而语无伦次。',
      sanityLoss: '0/0',
      rulebookRef: {
        source: 'rulebook',
        rulesetId: 'coc-7e-lite',
        entityId: 'npc-frightened-witness',
        entityType: 'npc_template',
        note: '套用受惊目击者模板，并替换为老宅邻居。',
      },
    },
  ],
  skillOptions: [
    { id: 'spotHidden', label: '侦查', group: '调查' },
    { id: 'listen', label: '聆听', group: '调查' },
    { id: 'occult', label: '神秘学', group: '学识' },
    { id: 'psychology', label: '心理学', group: '学识' },
    { id: 'medicine', label: '医学', group: '学识' },
    { id: 'firstAid', label: '急救', group: '学识' },
    { id: 'persuade', label: '说服', group: '社交' },
    { id: 'intimidate', label: '威吓', group: '社交' },
    { id: 'stealth', label: '潜行', group: '行动' },
    { id: 'locksmith', label: '开锁', group: '行动' },
    { id: 'brawl', label: '格斗', group: '战斗' },
    { id: 'firearms', label: '枪械', group: '战斗' },
  ],
  equipmentOptions: [
    '圣水',
    '银质十字',
    '驱魔符纸',
    '手电筒',
    '撬棍',
    '绳索',
    '急救包',
    '散弹枪',
    '左轮手枪',
    '盐',
    '蜡烛',
    '录音机',
  ],
  occupationOptions: [
    {
      id: 'occupation-priest',
      name: '神父',
      summary: '擅长驱邪与安抚人心。',
      skillIds: ['occult', 'persuade', 'psychology'],
      equipment: ['圣水', '银质十字', '驱魔符纸'],
    },
    {
      id: 'occupation-detective',
      name: '刑警',
      summary: '调查与战斗经验丰富。',
      skillIds: ['spotHidden', 'listen', 'firearms'],
      equipment: ['手电筒', '左轮手枪', '录音机'],
    },
    {
      id: 'occupation-folklore',
      name: '民俗学者',
      summary: '对民间秘闻与仪式有研究。',
      skillIds: ['occult', 'psychology', 'listen'],
      equipment: ['驱魔符纸', '蜡烛', '录音机'],
    },
    {
      id: 'occupation-veteran',
      name: '退伍军人',
      summary: '在危机时保持镇定。',
      skillIds: ['brawl', 'firearms', 'stealth'],
      equipment: ['散弹枪', '绳索', '手电筒'],
    },
    {
      id: 'occupation-private-eye',
      name: '私家侦探',
      summary: '擅长潜入与调查。',
      skillIds: ['spotHidden', 'locksmith', 'stealth'],
      equipment: ['撬棍', '手电筒', '录音机'],
    },
    {
      id: 'occupation-reporter',
      name: '记者',
      summary: '善于追踪线索与沟通。',
      skillIds: ['persuade', 'psychology', 'spotHidden'],
      equipment: ['录音机', '手电筒', '盐'],
    },
  ],
  originOptions: ['松柏镇', '灰木镇', '旧教堂区', '码头区', '郊外农场'],
  buffOptions: ['灵感加持', '沉着冷静', '仪式专注', '团队支援', '直觉敏锐'],
  debuffOptions: [],
  attributeRanges: {},
  attributePointBudget: 0,
  skillLimit: 4,
  equipmentLimit: 5,
  buffLimit: 1,
  debuffLimit: 0,
  rules: {},
  scenes: [
    {
      id: 'scene-mansion',
      title: '封锁的老宅',
      summary: '破门闯入，屋内尽是撕裂的护符与混乱痕迹。',
      location: '格林家的老宅',
      hooks: ['符纸残片', '烧毁的圣像', '孩童哭声'],
    },
    {
      id: 'scene-basement',
      title: '地下祈祷室',
      summary: '盐圈与刻痕围出祭坛，驱魔仪式在此达成。',
      location: '地下室祈祷间',
      hooks: ['盐圈', '刻痕', '破碎祭坛'],
    },
  ],
  encounters: [
    {
      id: 'encounter-cult',
      title: '邪教徒阻击',
      summary: '护法信徒阻挡外来者进入地下室。',
      npcs: ['邪教徒 x3'],
      danger: '中',
      difficultyIntent: 'moderate',
      riskNotes: '不应要求玩家正面杀穿，可用惊吓、驱散或绕行处理。',
      rulebookRefs: [
        {
          source: 'rulebook',
          rulesetId: 'coc-7e-lite',
          entityId: 'npc-cultist-basic',
          entityType: 'npc_template',
          count: 2,
          note: '地下室入口的低阶护法。',
        },
      ],
    },
    {
      id: 'encounter-possessed',
      title: '邪灵显形',
      summary: '附身孩童失控，邪灵在仪式中现形。',
      npcs: ['被附身的孩童 x1', '影灵 x1'],
      danger: '高',
      difficultyIntent: 'high',
      riskNotes: '战斗只是表象，核心解法应是仪式、限制行动和环境压制。',
      rulebookRefs: [
        {
          source: 'rulebook',
          rulesetId: 'coc-7e-lite',
          entityId: 'creature-minor-spirit',
          entityType: 'creature',
          count: 1,
          note: '附身仪式失败后显形的低阶怨灵。',
        },
      ],
    },
  ],
};
